name: Robot Lignelife Quotidien

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-robot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests
      - name: Lancer le robot peu importe sa position
        run: |
          FILE_PATH=$(find . -name "automatisation.py" -print -quit)
          if [ -z "$FILE_PATH" ]; then
            echo "❌ Erreur : Le fichier complet est introuvable sur votre compte !"
            exit 1
          fi
          python "$FILE_PATH"
